-- 用户表
CREATE TABLE `用户` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `用户名` VARCHAR(50) NOT NULL UNIQUE,
  `密码` VARCHAR(255) NOT NULL,
  `邮箱` VARCHAR(100) UNIQUE,
  `创建时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `更新时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4;

-- 角色表
CREATE TABLE `角色` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `角色名称` VARCHAR(50) NOT NULL UNIQUE
) DEFAULT CHARSET=utf8mb4;

-- 用户角色关联表
CREATE TABLE `用户角色` (
  `用户id` INT,
  `角色id` INT,
  PRIMARY KEY (`用户id`, `角色id`),
  FOREIGN KEY (`用户id`) REFERENCES `用户`(`id`),
  FOREIGN KEY (`角色id`) REFERENCES `角色`(`id`)
) DEFAULT CHARSET=utf8mb4;

-- 游戏分类表
CREATE TABLE `游戏分类` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `分类名称` VARCHAR(100) NOT NULL UNIQUE,
  `描述` TEXT,
  `创建时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `更新时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) DEFAULT CHARSET=utf8mb4;

-- 游戏表
CREATE TABLE `游戏` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `游戏名称` VARCHAR(255) NOT NULL,
  `描述` TEXT,
  `发行日期` DATE,
  `图片链接` VARCHAR(255),
  `分类id` INT,
  `创建时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `更新时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`分类id`) REFERENCES `游戏分类`(`id`)
) DEFAULT CHARSET=utf8mb4;

-- 评论表
CREATE TABLE `评论` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `评论内容` TEXT NOT NULL,
  `用户id` INT,
  `游戏id` INT,
  `创建时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `更新时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`用户id`) REFERENCES `用户`(`id`),
  FOREIGN KEY (`游戏id`) REFERENCES `游戏`(`id`)
) DEFAULT CHARSET=utf8mb4;

-- 评分表
CREATE TABLE `评分` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `分数` INT NOT NULL,
  `用户id` INT,
  `游戏id` INT,
  `创建时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `更新时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY `idx_用户_游戏` (`用户id`, `游戏id`),
  FOREIGN KEY (`用户id`) REFERENCES `用户`(`id`),
  FOREIGN KEY (`游戏id`) REFERENCES `游戏`(`id`)
) DEFAULT CHARSET=utf8mb4;

-- 收藏表
CREATE TABLE `收藏` (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `用户id` INT,
  `游戏id` INT,
  `收藏时间` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY `idx_用户_游戏` (`用户id`, `游戏id`),
  FOREIGN KEY (`用户id`) REFERENCES `用户`(`id`),
  FOREIGN KEY (`游戏id`) REFERENCES `游戏`(`id`)
) DEFAULT CHARSET=utf8mb4;
